### PR TITLE
Change collapse menu icon :: double-caret instead of single-caret

### PR DESCRIPTION
**Pull request by medou-boushab**
Screen Shot 2021-09-02 at 10 08 33 AM

Screen Shot 2021-09-02 at 10 08 44 AM

### CODE REVIEW

**Comment by medou-boushab** [comment]
Sorry for this long history PR list, I'll squash and merge when getting reviews

**Comment by amouhoub** [comment]
@medou-boushab  can you please post a screenshot ?

**Review by marounkoussaifi — APPROVED** [review]

**Review by fviale — APPROVED** [review]

**Comment by amouhoub** [comment]
@medou, please fix the following issues before merging :
- The vertical green bar which indicates which portal is selected disappears in compact mode (see your own screenshot)
- The margin between the double carets and the workflow execution portal is way too big. Please make it equal to the top margin of the double caret icon. top & bottom margins should be equal visually even though their values can be different.

**Comment by medou-boushab** [comment]
> @medou, please fix the following issues before merging :
> 
> * The vertical green bar which indicates which portal is selected disappears in compact mode (see your own screenshot)
It's there, I just didn't include it in my screenshot
> * The margin between the double carets and the workflow execution portal is way too big. Please make it equal to the top margin of the double caret icon. top & bottom margins should be equal visually even though their values can be different.
OK

**Pull request merged**
